displayName=Cursor Clarity
author=Effie
description=Draws a highlighted ring around your mouse cursor for better visibility during combat.
support=https://github.com/Aidoyk/Cursor-Circle-OSRS
projectUrl=https://github.com/Aidoyk/Cursor-Circle-OSRS
plugins=com.cursorclarity.CursorClarityPlugin
